version: '2'

services:

  syges-interface:
    build:  ./syges-interface
    hostname: syges-interface
    env_file: ./syges-interface/db-connection.env
    environment:
      - PORT=3001
      - DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3001:3001
    links:
      - syges-database

  syges-database:
    build: ./syges-database
    hostname: syges-database
    environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./persistent/syges-database:/var/lib/mysql